SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
BACKGROUND_COLOR = "black"

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_COLOR = "red"
ASTEROID_LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_COLOR = "green"
PLAYER_LINE_WIDTH = 2
PLAYER_SPAWN_X = 0.5 * SCREEN_WIDTH
PLAYER_SPAWN_Y = 0.5 * SCREEN_HEIGHT
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5
SHOT_COLOR = "white"
SHOT_LINE_WIDTH = 2
